// <auto-generated />
using System;
using AddressBook.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AddressBook.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AddressBookDbContext))]
    [Migration("20260610234021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AddressBook.Application.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Address = "12 Baker Street, London",
                            FirstName = "John",
                            LastName = "Smith",
                            PhoneNumber = "+44 20 7946 0001"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Address = "45 Oxford Road, Manchester",
                            FirstName = "Emma",
                            LastName = "Johnson",
                            PhoneNumber = "+44 161 496 0002"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Address = "Slovenska cesta 10, Ljubljana",
                            FirstName = "Luka",
                            LastName = "Novak",
                            PhoneNumber = "+386 1 234 0003"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Address = "Celovska cesta 25, Ljubljana",
                            FirstName = "Ana",
                            LastName = "Horvat",
                            PhoneNumber = "+386 1 234 0004"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Address = "Via Roma 3, Trieste",
                            FirstName = "Marco",
                            LastName = "Rossi",
                            PhoneNumber = "+39 040 555 0005"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Address = "Via Garibaldi 18, Milano",
                            FirstName = "Giulia",
                            LastName = "Bianchi",
                            PhoneNumber = "+39 02 555 0006"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Address = "Hauptstraße 7, Berlin",
                            FirstName = "Hans",
                            LastName = "Müller",
                            PhoneNumber = "+49 30 555 0007"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Address = "Bahnhofstraße 21, München",
                            FirstName = "Anna",
                            LastName = "Schmidt",
                            PhoneNumber = "+49 89 555 0008"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Address = "Rue de Rivoli 14, Paris",
                            FirstName = "Pierre",
                            LastName = "Dubois",
                            PhoneNumber = "+33 1 4555 0009"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Address = "Avenue Victor Hugo 8, Lyon",
                            FirstName = "Marie",
                            LastName = "Laurent",
                            PhoneNumber = "+33 4 7855 0010"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Address = "Calle Mayor 5, Madrid",
                            FirstName = "Carlos",
                            LastName = "García",
                            PhoneNumber = "+34 91 555 0011"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Address = "Gran Vía 32, Barcelona",
                            FirstName = "Lucía",
                            LastName = "Martínez",
                            PhoneNumber = "+34 93 555 0012"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Address = "Damstraat 9, Amsterdam",
                            FirstName = "Jan",
                            LastName = "de Vries",
                            PhoneNumber = "+31 20 555 0013"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Address = "Kerkstraat 11, Utrecht",
                            FirstName = "Sanne",
                            LastName = "Bakker",
                            PhoneNumber = "+31 30 555 0014"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Address = "Storgatan 2, Stockholm",
                            FirstName = "Erik",
                            LastName = "Andersson",
                            PhoneNumber = "+46 8 555 0015"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Address = "Karl Johans gate 4, Oslo",
                            FirstName = "Ingrid",
                            LastName = "Larsen",
                            PhoneNumber = "+47 22 55 0016"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Address = "742 Evergreen Terrace, Springfield",
                            FirstName = "James",
                            LastName = "Brown",
                            PhoneNumber = "+1 217 555 0017"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Address = "350 Fifth Avenue, New York",
                            FirstName = "Olivia",
                            LastName = "Davis",
                            PhoneNumber = "+1 212 555 0018"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Address = "221 Queen Street, Toronto",
                            FirstName = "Liam",
                            LastName = "Wilson",
                            PhoneNumber = "+1 416 555 0019"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Address = "88 George Street, Sydney",
                            FirstName = "Sophia",
                            LastName = "Taylor",
                            PhoneNumber = "+61 2 5550 0020"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Address = "Trubarjeva ulica 33, Maribor",
                            FirstName = "Peter",
                            LastName = "Kovač",
                            PhoneNumber = "+386 2 234 0021"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Address = "Prešernova ulica 1, Kranj",
                            FirstName = "Maja",
                            LastName = "Zupančič",
                            PhoneNumber = "+386 4 234 0022"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Address = "Václavské náměstí 12, Praha",
                            FirstName = "Tomáš",
                            LastName = "Novák",
                            PhoneNumber = "+420 2 5550 0023"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Address = "ul. Marszałkowska 6, Warszawa",
                            FirstName = "Katarzyna",
                            LastName = "Kowalska",
                            PhoneNumber = "+48 22 555 0024"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Address = "Váci utca 19, Budapest",
                            FirstName = "András",
                            LastName = "Nagy",
                            PhoneNumber = "+36 1 555 0025"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Address = "Strada Lipscani 27, București",
                            FirstName = "Elena",
                            LastName = "Popescu",
                            PhoneNumber = "+40 21 555 0026"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Address = "Ermou 15, Athens",
                            FirstName = "Dimitris",
                            LastName = "Papadopoulos",
                            PhoneNumber = "+30 21 0555 0027"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            Address = "1-2-3 Shibuya, Tokyo",
                            FirstName = "Yuki",
                            LastName = "Tanaka",
                            PhoneNumber = "+81 3 5550 0028"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            Address = "Nanjing Road 100, Shanghai",
                            FirstName = "Wei",
                            LastName = "Chen",
                            PhoneNumber = "+86 21 5550 0029"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            Address = "Linking Road 55, Mumbai",
                            FirstName = "Aisha",
                            LastName = "Khan",
                            PhoneNumber = "+91 22 5550 0030"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
